hs.hotkey.bind({"cmd", "ctrl"}, "u", function()
  hs.application.open("Firefox Developer Edition.app")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "i", function()
  hs.application.open("iTerm.app")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "v", function()
  hs.application.open("Visual Studio Code.app")
end)
